const buttonsData = {
	buttonsRow1: [
		{ id: 1, className: "btn1 btn-line1", value: 1, row: 1, column: 1 },
		{ id: 2, className: "btn2 btn-line1", value: 2, row: 1, column: 2 },
		{ id: 3, className: "btn3 btn-line1", value: 3, row: 1, column: 3 },
		{ id: 4, className: "btn4 btn-line1", value: 4, row: 1, column: 4 },
		{ id: 5, className: "btn5 btn-line1", value: 5, row: 1, column: 5 },
		{ id: 6, className: "btn6 btn-line1", value: 6, row: 1, column: 6 },
		{ id: 7, className: "btn7 btn-line1", value: 7, row: 1, column: 7 },
		{ id: 8, className: "btn8 btn-line1", value: 8, row: 1, column: 8 },
		{ id: 9, className: "btn9 btn-line1", value: 9, row: 1, column: 9 },
		{ id: 10, className: "btn10 btn-line1", value: 10, row: 1, column: 10 },
		{ id: 11, value: 11, row: 1, column: 11 },
	],
	buttonsRow2: [
		{
			id: 12,
			className: "btn1 btn-line-even tent",
			value: 1,
			row: 2,
			column: 1,
		},
		{ id: 13, className: "btn2 btn-line-even", value: 2, row: 2, column: 2 },
		{ id: 14, className: "btn3 btn-line-even", value: 3, row: 2, column: 3 },
		{ id: 15, className: "btn4 btn-line-even", value: 4, row: 2, column: 4 },
		{
			id: 16,
			className: "btn5 btn-line-even grass",
			value: 5,
			row: 2,
			column: 5,
		},
		{ id: 17, className: "btn6 btn-line-even", value: 6, row: 2, column: 6 },
		{
			id: 18,
			className: "btn7 btn-line-even stone",
			value: 7,
			row: 2,
			column: 7,
		},
		{ id: 19, className: "btn8 btn-line-even", value: 8, row: 2, column: 8 },
		{ id: 20, className: "btn9 btn-line-even", value: 9, row: 2, column: 9 },
		{ id: 21, className: "btn10 btn-line-even", value: 10, row: 2, column: 10 },
	],
	buttonsRow3: [
		{ id: 23, className: "btn1 btn-line-odd", value: 1, row: 3, column: 1 },
		{ id: 24, className: "btn2 btn-line-odd", value: 2, row: 3, column: 2 },
		{ id: 25, className: "btn3 btn-line-odd", value: 3, row: 3, column: 3 },
		{
			id: 26,
			className: "btn4 btn-line-odd wood",
			value: 4,
			row: 3,
			column: 4,
		},
		{ id: 27, className: "btn5 btn-line-odd", value: 5, row: 3, column: 5 },
		{ id: 28, className: "btn6 btn-line-odd", value: 6, row: 3, column: 6 },
		{ id: 29, className: "btn7 btn-line-odd", value: 7, row: 3, column: 7 },
		{ id: 30, className: "btn8 btn-line-odd", value: 8, row: 3, column: 8 },
		{ id: 31, className: "btn9 btn-line-odd", value: 9, row: 3, column: 9 },
		{ id: 32, className: "btn10 btn-line-odd", value: 10, row: 3, column: 10 },
		{ id: 33, className: "btn11 btn-line-odd", value: 11, row: 3, column: 11 },
	],
	buttonsRow4: [
		{ id: 34, className: "btn1 btn-line-even", value: 1, row: 4, column: 1 },
		{
			id: 35,
			className: "btn2 btn-line-even stone",
			value: 2,
			row: 4,
			column: 2,
		},
		{ id: 36, className: "btn3 btn-line-even", value: 3, row: 4, column: 3 },
		{ id: 37, className: "btn4 btn-line-even", value: 4, row: 4, column: 4 },
		{ id: 38, className: "btn5 btn-line-even", value: 5, row: 4, column: 5 },
		{ id: 39, className: "btn6 btn-line-even", value: 6, row: 4, column: 6 },
		{ id: 40, className: "btn7 btn-line-even", value: 7, row: 4, column: 7 },
		{
			id: 41,
			className: "btn8 btn-line-even grass",
			value: 8,
			row: 4,
			column: 8,
		},
		{ id: 42, className: "btn9 btn-line-even", value: 9, row: 4, column: 9 },
		{ id: 43, className: "btn10 btn-line-even", value: 10, row: 4, column: 10 },
	],
	buttonsRow5: [
		{
			id: 45,
			className: "btn1 btn-line-odd flint",
			value: 1,
			row: 5,
			column: 1,
		},
		{ id: 46, className: "btn2 btn-line-odd", value: 2, row: 5, column: 2 },
		{ id: 47, className: "btn3 btn-line-odd", value: 3, row: 5, column: 3 },
		{ id: 48, className: "btn4 btn-line-odd", value: 4, row: 5, column: 4 },
		{ id: 49, className: "btn5 btn-line-odd", value: 5, row: 5, column: 5 },
		{
			id: 50,
			className: "btn6 btn-line-odd fire",
			value: 6,
			row: 5,
			column: 6,
		},
		{ id: 51, className: "btn7 btn-line-odd", value: 7, row: 5, column: 7 },
		{ id: 52, className: "btn8 btn-line-odd", value: 8, row: 5, column: 8 },
		{ id: 53, className: "btn9 btn-line-odd", value: 9, row: 5, column: 9 },
		{ id: 54, className: "btn10 btn-line-odd", value: 10, row: 5, column: 10 },
		{ id: 55, className: "btn11 btn-line-odd", value: 11, row: 5, column: 11 },
	],
	buttonsRow6: [
		{ id: 56, className: "btn1 btn-line-even", value: 1, row: 6, column: 1 },
		{ id: 57, className: "btn2 btn-line-even", value: 2, row: 6, column: 2 },
		{
			id: 58,
			className: "btn3 btn-line-even grass",
			value: 3,
			row: 6,
			column: 3,
		},
		{ id: 59, className: "btn4 btn-line-even", value: 4, row: 6, column: 4 },
		{ id: 60, className: "btn5 btn-line-even", value: 5, row: 6, column: 5 },
		{ id: 61, className: "btn6 btn-line-even", value: 6, row: 6, column: 6 },
		{
			id: 62,
			className: "btn7 btn-line-even wood",
			value: 7,
			row: 6,
			column: 7,
		},
		{ id: 63, className: "btn8 btn-line-even", value: 8, row: 6, column: 8 },
		{ id: 64, className: "btn9 btn-line-even", value: 9, row: 6, column: 9 },
		{
			id: 65,
			className: "btn10 btn-line-even flint",
			value: 10,
			row: 6,
			column: 10,
		},
	],
	buttonsRow7: [
		{ id: 67, className: "btn1 btn-line-odd", value: 1, row: 7, column: 1 },
		{ id: 68, className: "btn2 btn-line-odd", value: 2, row: 7, column: 2 },
		{ id: 69, className: "btn3 btn-line-odd", value: 3, row: 7, column: 3 },
		{ id: 70, className: "btn4 btn-line-odd", value: 4, row: 7, column: 4 },
		{ id: 71, className: "btn5 btn-line-odd", value: 5, row: 7, column: 5 },
		{ id: 72, className: "btn6 btn-line-odd", value: 6, row: 7, column: 6 },
		{ id: 73, className: "btn7 btn-line-odd", value: 7, row: 7, column: 7 },
		{ id: 74, className: "btn8 btn-line-odd", value: 8, row: 7, column: 8 },
		{ id: 75, className: "btn9 btn-line-odd", value: 9, row: 7, column: 9 },
		{ id: 76, className: "btn10 btn-line-odd", value: 10, row: 7, column: 10 },
		{ id: 77, className: "btn11 btn-line-odd", value: 11, row: 7, column: 11 },
	],
	buttonsRow8: [
		{ id: 78, className: "btn1 btn-line-even", value: 1, row: 8, column: 1 },
		{ id: 79, className: "btn2 btn-line-even", value: 2, row: 8, column: 2 },
		{ id: 80, className: "btn3 btn-line-even", value: 3, row: 8, column: 3 },
		{ id: 81, className: "btn4 btn-line-even", value: 4, row: 8, column: 4 },
		{ id: 82, className: "btn5 btn-line-even", value: 5, row: 8, column: 5 },
		{ id: 83, className: "btn6 btn-line-even", value: 6, row: 8, column: 6 },
		{ id: 84, className: "btn7 btn-line-even", value: 7, row: 8, column: 7 },
		{ id: 85, className: "btn8 btn-line-even", value: 8, row: 8, column: 8 },
		{ id: 86, className: "btn9 btn-line-even", value: 9, row: 8, column: 9 },
		{
			id: 87,
			className: "btn10 btn-line-even lotos",
			value: 10,
			row: 8,
			column: 10,
		},
	],
	buttonsRow9: [
		{ id: 89, className: "btn1 btn-line-odd", value: 1, row: 9, column: 1 },
		{
			id: 90,
			className: "btn2 btn-line-odd stone",
			value: 2,
			row: 9,
			column: 2,
		},
		{ id: 91, className: "btn3 btn-line-odd", value: 3, row: 9, column: 3 },
		{ id: 92, className: "btn4 btn-line-odd", value: 4, row: 9, column: 4 },
		{ id: 93, className: "btn5 btn-line-odd", value: 5, row: 9, column: 5 },
		{ id: 94, className: "btn6 btn-line-odd", value: 6, row: 9, column: 6 },
		{ id: 95, className: "btn7 btn-line-odd", value: 7, row: 9, column: 7 },
		{
			id: 96,
			className: "btn8 btn-line-odd grass",
			value: 8,
			row: 9,
			column: 8,
		},
		{
			id: 97,
			className: "btn9 btn-line-odd oasis",
			value: 9,
			row: 9,
			column: 9,
		},
		{ id: 98, className: "btn10 btn-line-odd", value: 10, row: 9, column: 10 },
		{ id: 99, className: "btn11 btn-line-odd", value: 11, row: 9, column: 11 },
	],
	buttonsRow10: [
		{ id: 100, className: "btn1 btn-line-even", value: 1, row: 10, column: 1 },
		{ id: 101, className: "btn2 btn-line-even", value: 2, row: 10, column: 2 },
		{
			id: 102,
			className: "btn3 btn-line-even frozen-crown",
			value: 3,
			row: 10,
			column: 3,
		},
		{ id: 103, className: "btn4 btn-line-even", value: 4, row: 10, column: 4 },
		{
			id: 104,
			className: "btn5 btn-line-even flint",
			value: 5,
			row: 10,
			column: 5,
		},
		{ id: 105, className: "btn6 btn-line-even", value: 6, row: 10, column: 6 },
		{ id: 106, className: "btn7 btn-line-even", value: 7, row: 10, column: 7 },
		{ id: 107, className: "btn8 btn-line-even", value: 8, row: 10, column: 8 },
		{
			id: 108,
			className: "btn9 btn-line-even wood",
			value: 9,
			row: 10,
			column: 10,
		},
		{
			id: 109,
			className: "btn10 btn-line-even",
			value: 10,
			row: 10,
			column: 11,
		},
	],
	buttonsRow11: [
		{ id: 111, className: "btn1 btn-line-odd", value: 1, row: 11, column: 1 },
		{ id: 112, className: "btn2 btn-line-odd", value: 2, row: 11, column: 2 },
		{ id: 113, className: "btn3 btn-line-odd", value: 3, row: 11, column: 3 },
		{ id: 114, className: "btn4 btn-line-odd", value: 4, row: 11, column: 4 },
		{ id: 115, className: "btn5 btn-line-odd", value: 5, row: 11, column: 5 },
		{ id: 116, className: "btn6 btn-line-odd", value: 6, row: 11, column: 6 },
		{ id: 117, className: "btn7 btn-line-odd", value: 7, row: 11, column: 7 },
		{ id: 118, className: "btn8 btn-line-odd", value: 8, row: 11, column: 8 },
		{ id: 119, className: "btn9 btn-line-odd", value: 9, row: 11, column: 9 },
		{
			id: 120,
			className: "btn10 btn-line-odd",
			value: 10,
			row: 11,
			column: 10,
		},
		{
			id: 121,
			className: "btn11 btn-line-odd flint",
			value: 11,
			row: 11,
			column: 11,
		},
	],
	buttonsRow12: [
		{ id: 122, className: "btn1 btn-line-even", value: 1, row: 12, column: 1 },
		{ id: 123, className: "btn2 btn-line-even", value: 2, row: 12, column: 2 },
		{ id: 124, className: "btn3 btn-line-even", value: 3, row: 12, column: 3 },
		{ id: 125, className: "btn4 btn-line-even", value: 4, row: 12, column: 4 },
		{ id: 126, className: "btn5 btn-line-even", value: 5, row: 12, column: 5 },
		{ id: 127, className: "btn6 btn-line-even", value: 6, row: 12, column: 6 },
		{ id: 128, className: "btn7 btn-line-even", value: 7, row: 12, column: 7 },
		{ id: 129, className: "btn8 btn-line-even", value: 8, row: 12, column: 8 },
		{ id: 130, className: "btn9 btn-line-even", value: 9, row: 12, column: 9 },
		{
			id: 131,
			className: "btn10 btn-line-even",
			value: 10,
			row: 12,
			column: 10,
		},
	],
	buttonsRow13: [
		{ id: 133, className: "btn1 btn-line-odd", value: 1, row: 13, column: 1 },
		{ id: 134, className: "btn2 btn-line-odd", value: 2, row: 13, column: 2 },
		{ id: 135, className: "btn3 btn-line-odd", value: 3, row: 13, column: 3 },
		{ id: 136, className: "btn4 btn-line-odd", value: 4, row: 13, column: 4 },
		{ id: 137, className: "btn5 btn-line-odd", value: 5, row: 13, column: 5 },
		{ id: 138, className: "btn6 btn-line-odd", value: 6, row: 13, column: 6 },
		{
			id: 139,
			className: "btn7 btn-line-odd stone",
			value: 7,
			row: 13,
			column: 7,
		},
		{ id: 140, className: "btn8 btn-line-odd", value: 8, row: 13, column: 8 },
		{ id: 141, className: "btn9 btn-line-odd", value: 9, row: 13, column: 9 },
		{
			id: 142,
			className: "btn10 btn-line-odd",
			value: 10,
			row: 13,
			column: 10,
		},
		{
			id: 143,
			className: "btn11 btn-line-odd",
			value: 11,
			row: 13,
			column: 11,
		},
	],
	buttonsRow14: [
		{
			id: 144,
			className: "btn1 btn-line-even stone",
			value: 1,
			row: 14,
			column: 1,
		},
		{ id: 145, className: "btn2 btn-line-even", value: 2, row: 14, column: 2 },
		{ id: 146, className: "btn3 btn-line-even", value: 3, row: 14, column: 3 },
		{
			id: 147,
			className: "btn4 btn-line-even fire",
			value: 4,
			row: 14,
			column: 4,
		},
		{ id: 148, className: "btn5 btn-line-even", value: 5, row: 14, column: 5 },
		{ id: 149, className: "btn6 btn-line-even", value: 6, row: 14, column: 6 },
		{ id: 150, className: "btn7 btn-line-even", value: 7, row: 14, column: 7 },
		{ id: 151, className: "btn8 btn-line-even", value: 8, row: 14, column: 8 },
		{ id: 152, className: "btn9 btn-line-even", value: 9, row: 14, column: 9 },
		{
			id: 153,
			className: "btn10 btn-line-even",
			value: 10,
			row: 14,
			column: 10,
		},
	],
	buttonsRow15: [
		{ id: 154, className: "btn1 btn-line-odd", value: 1, row: 15, column: 1 },
		{ id: 155, className: "btn2 btn-line-odd", value: 2, row: 15, column: 2 },
		{
			id: 156,
			className: "btn3 btn-line-odd wood",
			value: 3,
			row: 15,
			column: 3,
		},
		{ id: 157, className: "btn4 btn-line-odd", value: 4, row: 15, column: 4 },
		{ id: 158, className: "btn5 btn-line-odd", value: 5, row: 15, column: 5 },
		{ id: 159, className: "btn6 btn-line-odd", value: 6, row: 15, column: 6 },
		{ id: 160, className: "btn7 btn-line-odd", value: 7, row: 15, column: 7 },
		{ id: 161, className: "btn8 btn-line-odd", value: 8, row: 15, column: 8 },
		{
			id: 162,
			className: "btn9 btn-line-odd stone",
			value: 9,
			row: 15,
			column: 9,
		},
		{
			id: 163,
			className: "btn10 btn-line-odd",
			value: 10,
			row: 15,
			column: 10,
		},
		{
			id: 164,
			className: "btn11 btn-line-odd",
			value: 11,
			row: 15,
			column: 11,
		},
	],
	buttonsRow16: [
		{
			id: 165,
			className: "btn1 btn-line-even cave",
			value: 1,
			row: 16,
			column: 1,
		},
		{ id: 166, className: "btn2 btn-line-even", value: 2, row: 16, column: 2 },
		{ id: 167, className: "btn3 btn-line-even", value: 3, row: 16, column: 3 },
		{ id: 168, className: "btn4 btn-line-even", value: 4, row: 16, column: 4 },
		{
			id: 169,
			className: "btn5 btn-line-even grass",
			value: 5,
			row: 16,
			column: 5,
		},
		{ id: 170, className: "btn6 btn-line-even", value: 6, row: 16, column: 6 },
		{
			id: 171,
			className: "btn7 btn-line-even lotos",
			value: 7,
			row: 16,
			column: 7,
		},
		{ id: 172, className: "btn8 btn-line-even", value: 8, row: 16, column: 8 },
		{ id: 173, className: "btn9 btn-line-even", value: 9, row: 16, column: 9 },
		{
			id: 174,
			className: "btn10 btn-line-even boss",
			value: 10,
			row: 16,
			column: 10,
		},
	],
};

export default buttonsData;
